config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :comments
  end
  
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]
	def create
		@post = Post.find(params[:post_id]) 
		@comment = @post.comments.build(comment_params)
		@comment.user = current_user
		@comment.save
		redirect_to post_path(@post)
	end
	def destroy
    	@post = Post.find(params[:post_id])
    	@comment = @post.comments.find(params[:id])
    	@comment.destroy
    	redirect_to post_path(@post)
 end


private
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all
	end
	def new
		@post = Post.new
	end
	def create
		@post = current_user.posts.build(post_params) 
		if @post.save
			redirect_to posts_path
		else
			render :new
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit 
		@post = Post.find(params[:id])
	  	can_user_edit
	end 


	def update 
		@post = Post.find(params[:id])
	  	can_user_edit 

		if @post.update(post_params)
			redirect_to posts_path
		else	
			render 'edit'
		end
	end

	  def destroy 
		@post = Post.find(params[:id])
    	can_user_edit
		
		@post.destroy

		redirect_to posts_path
  end




end

private
	
	def can_user_edit
		if (@post.user != current_user)
			redirect_to posts_path
		end
	end

	def post_params
		params.require(:post).permit(:text, :photo, :public?)
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def allowed_to_view(post)
	 (post.user == current_user)
			
	end
end

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	
	
	<p>
		<%= f.label :body %><br>
    	<%= f.text_area :body %>
	</p>
	
	<p>
    	<%= f.submit "Click here Bru"%>
	</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brugram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if user_signed_in? %> Logged in as <strong><%= current_user.email %></strong>.
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
<% else %>
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>
</head>
<body>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<p>
	<%= f.label :text, "Caption" %>
	<%= f.text_area :text %>
	</p>
	<p>
	<%= f.label :photo, "URL" %>
	<%= f.text_area :photo %>
	</p>
	<p>
	<%= label_tag ("Should this be public?") %>
	<%= f.select :public, [true,false] %>
	</p>

	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1> Edit your stuff</h1>

<%= render "form" %>

<%= link_to "Back", posts_path %>

app/views/posts/index.html.erb
<h1> Welcome to Brugram! </h1>

<p><%= link_to "New Post", new_post_path %></p>

<% @posts.each do |post| %>

<h1><%= link_to post.text, post_path(post) %></h1> 
<h1> This was posted by <%= post.user.email %></h1>
<img src="<%= post.photo %>"> 
<p>
	<% if allowed_to_view(post) %>
	<%= link_to "Edit", edit_post_path(post) %> |
	<%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
    <% end %>
</p>


<% end %>

app/views/posts/new.html.erb
<h1> This is the new page </h1>

<%= render "form" %>

<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.text %> page</h1>
<h1>This was posted by <%= @post.user.email %></h1>
<img src="<%= @post.photo %>"> 
<p>
	<% if allowed_to_view(@post) %>
	<%= link_to "Edit", edit_post_path(@post) %> |
	<%= link_to 'Destroy', post_path(@post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> |
    <% end %>
<%= link_to "Back", posts_path %>    
</p>


<h2>Comments</h2>

<% @post.comments.each do |comment| %>
  
  <p>

    <strong>Comment:</strong>
    <%= comment.body %>

    <% if (current_user == comment.user) %>

    <%= link_to 'Destroy', post_comment_path(@post, comment),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </p>
  
  <% end %>

<% end %>

<h2>Add a comment:</h2>

<%= render "comments/form" %>